from google.adk.agents import Agent, ParallelAgent, LoopAgent, SequentialAgent
from google.adk.models.google_llm import Gemini
from google.adk.runners import InMemoryRunner
from google.adk.tools import google_search, FunctionTool, AgentTool
from google.genai import types


retry_config = types.HttpRetryOptions(
    attempts=5,  # Maximum retry attempts
    exp_base=7,  # Delay multiplier
    initial_delay=1,  # Initial delay before first retry (in seconds)
    http_status_codes=[429, 500, 503, 504],  # Retry on these HTTP errors
)

LITE_MODEL = "gemini-2.5-flash-lite"

research_agent = Agent(
    name="research_agent",
    model=Gemini(model=LITE_MODEL, retry_options=retry_config),
    description="A research agent that can research topics.",
    instruction="You are a research assistant. Based on the user prompt use Google Search to search for information about the requested topic. Include at least 3 different sources. Keep the report concise (300 words). Include 2-3 key quotes per source.  Include APA citations for each source used.",
    output_key="research_report",
    tools=[google_search],
)

outline_agent = Agent(
    name="outline_agent",
    model=Gemini(model=LITE_MODEL, retry_options=retry_config),
    instruction="You're tasked with taking the {research_report} and creating a concise outline for an essay. The outline should include an engaging introduction, 3-5 main points with subpoints, and a conclusion that summarizes the key takeaways. Ensure the outline is well-structured and easy to follow. Make sure to include atleast 1 quote per paragraph. Incude the APA citations as well.",
    output_key="outline_report",
    tools=[google_search],
)

initial_agent_writer = Agent(
    name="initial_writer_agent",
    model=Gemini(model=LITE_MODEL, retry_options=retry_config),
    instruction="You're tasked with taking the {outline_report} and creating a first draft for an essay. The essay should follow the outline closely, ensuring each main point and subpoint is thoroughly covered. Use engaging language to captivate the reader, and make sure to integrate quotes naturally into the text. The essay should have a clear introduction, body, and conclusion. Cite all sources in APA format.",
    output_key="current_draft_essay",
    tools=[google_search],
)

critic_agent = Agent(
    name="CriticAgent",
    model=Gemini(model=LITE_MODEL, retry_options=retry_config),
    instruction="""You are a constructive essay critic. Review the essay provided below.
    Essay: {current_draft_essay}

    Evaluate the essay's structure, argumentation, and use of evidence.
    - If the essay is well-written and complete, you MUST respond with the exact phrase: "APPROVED"
    - Otherwise, provide 2-3 specific, actionable suggestions for improvement.""",
    output_key="critique",  # Stores the feedback in the state.
)

ml_detection_agent = Agent(
    name="MLDetectionAgent",
    model=Gemini(model=LITE_MODEL, retry_options=retry_config),
    instruction="""You are a machine learning model detection tool. Review the essay provided below.
    Essay: {current_draft_essay}

    Evaluate the essay for signs of being generated by a machine learning model.
    - If you determine the essay is likely generated by a machine learning model, you MUST respond with the exact phrase: "APPROVED"
    - Otherwise, provide a brief explanation of why you believe the essay is human-written.""",
    output_key="mldetection",  # Stores the feedback in the state.
)


def exit_loop():
    """Call this function ONLY when the critique is 'APPROVED' and mldetection is 'APPROVED', indicating the essay is finished and no more changes are needed."""
    return {"status": "approved", "message": "Essay approved. Exiting refinement loop."}


refiner_agent = Agent(
    name="RefinerAgent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction="""You are a essay refiner. You have a essay draft, a critique, and a ML detection result.

    Essay Draft: {current_draft_essay}
    Critique: {critique}
    ML Detection: {mldetection}

    Your task is to analyze the critique and ML detection result.
    - IF the critique is EXACTLY "APPROVED" and the ML Detection is "APPROVED", you MUST call the `exit_loop` function and nothing else.
    - OTHERWISE, rewrite the essay draft to fully incorporate the feedback from the critique and ML detection result.""",
    output_key="current_draft_essay",  # It overwrites the essay with the new, refined version.
    tools=[
        FunctionTool(exit_loop)
    ],  # The tool is now correctly initialized with the function reference.
)

parallel_critique_team = ParallelAgent(
    name="ParallelCritiqueTeam",
    sub_agents=[critic_agent, ml_detection_agent],
)

editing_loop_agent = LoopAgent(
    name="EditingLoopAgent",
    sub_agents=[
        parallel_critique_team,
        refiner_agent,
    ],
    max_iterations=2,
)

root_agent = SequentialAgent(
    name="ResearchSystem",
    sub_agents=[
        research_agent,
        outline_agent,
        initial_agent_writer,
        editing_loop_agent,
    ],
)


runner = InMemoryRunner(agent=root_agent)

user_id = "debug_user"
session_id = "debug_session"


async def run():
    await runner.session_service.create_session(
        app_name=runner.app_name,
        user_id=user_id,
        session_id=session_id,
    )

    await runner.run(
        "Research and write a concise essay on the impact of climate change on global agriculture.",
        user_id=user_id,
        session_id=session_id,
    )
    session = await runner.session_service.get_session(
        app_name=runner.app_name,
        user_id=user_id,
        session_id=session_id,
    )
    current_draft_essay = session.state.get("current_draft_essay")
    print(current_draft_essay)
